#!/usr/bin/env python3
"""Lab double-run CI harness — the executable form of Appendix B's claim.

For each lab chapter (20-23) this script runs the lab's pytest suite TWICE,
each time in a fresh temp copy of the ``code/`` tree. The shipped tree is
never touched (no key is ever copied into it, no stub is ever edited):

  RED   — as shipped. The suite MUST fail in exactly the documented way:
          Lab 1: collection error (``pipeline.py`` is not shipped);
          Lab 2: all 10 tests fail with the "Lab 2 RED" NotImplementedError;
          Lab 3: all 8 tests error at fixture setup with the "LAB TODO 1"
                 NotImplementedError;
          Lab 4: 5 tests fail with the "Lab 4" NotImplementedError and
                 exactly one passes — ``test_in_sample_sharpe_is_seductive``,
                 the documented passing trap (it passes on the fixture
                 itself and is the reason the other tests exist).
          Any deviation — an unexpected pass, an unexpected failure mode,
          a wrong count — fails the harness.

  GREEN — with the Appendix B answer key spliced in, the way the appendix
          describes ("splice the key into the lab directory the way your CI
          would"): Lab 1's key is copied to ``pipeline.py``; Labs 2-4's keys
          are copied in and a generated ``conftest.py`` replaces the lab's
          RED stubs with the key's reference implementations before fixtures
          run. Every test MUST pass, and the count must match the lab's
          documented size (9/10/8/6).

Exit 0 only if every lab is RED-as-documented AND GREEN. Emits a JSON
report (``--json PATH``) and prints a human summary. Idempotent: every run
uses fresh temp dirs and overwrites the report.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CODE = REPO / "code"
APP_B = CODE / "app_b"

PYTEST_TIMEOUT_S = 600

# ---------------------------------------------------------------------------
# Lab specs. ``splice`` is either {"copy_as": <name>} (Lab 1: the key IS the
# missing module) or {"patch": {test_module_attr: "key_module.attr", ...}}
# (Labs 2-4: a generated conftest swaps the RED stubs for the key's names).
# ---------------------------------------------------------------------------
LABS = [
    {
        "chapter": "ch20",
        "lab": "Lab 1 — Market-Data Evidence Pipeline",
        "test_file": "test_lab1_data.py",
        "n_tests": 10,
        "key": "lab1_pipeline.py",
        "splice": {"copy_as": "pipeline.py"},
        "red": {"kind": "collection_error", "marker": "pipeline"},
    },
    {
        "chapter": "ch21",
        "lab": "Lab 2 — Signal Generator Contract",
        "test_file": "test_lab2_signals.py",
        "n_tests": 10,
        "key": "lab2_signal_pipeline.py",
        "splice": {"patch": {"SignalPipeline": "lab2_signal_pipeline.SignalPipeline"}},
        "red": {"kind": "all_fail", "marker": "Lab 2 RED"},
    },
    {
        "chapter": "ch22",
        "lab": "Lab 3 — Execution Under Fire",
        "test_file": "test_lab3_execution.py",
        "n_tests": 8,
        "key": "lab3_solution.py",
        "splice": {
            "patch": {
                "wire_desk": "lab3_solution.wire_desk",
                "submit_intent": "lab3_solution.submit_intent",
                "drive_market": "lab3_solution.drive_market",
                "close_out": "lab3_solution.close_out",
            }
        },
        "red": {"kind": "all_fail", "marker": "LAB TODO 1"},
    },
    {
        "chapter": "ch23",
        "lab": "Lab 4 — Walk-Forward Verdict",
        "test_file": "test_lab4_verify.py",
        "n_tests": 6,
        "key": "lab4_solution.py",
        "splice": {
            "patch": {
                "build_folds": "lab4_solution.build_folds",
                "verify_strategy": "lab4_solution.verify_strategy",
            }
        },
        "red": {
            "kind": "fail_except",
            "marker": "Lab 4",
            "allowed_pass": ["test_in_sample_sharpe_is_seductive"],
        },
    },
]

CONFTEST_TEMPLATE = '''"""Generated by ci_double_run.py (GREEN run only).

Replaces this lab's RED stubs with the Appendix B answer key's reference
implementations, before any fixture runs. The shipped lab files are
untouched — this conftest exists only in the temp GREEN copy.
"""
import {test_module} as _lab
import {key_module} as _key

{patch_lines}
'''


# ---------------------------------------------------------------------------
# pytest runner (junit XML -> structured results)
# ---------------------------------------------------------------------------
def run_pytest(lab_dir: Path) -> dict:
    """Run the lab's suite in lab_dir; return per-test outcomes."""
    xml_path = lab_dir / "junit.xml"
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "--tb=short",
         f"--junitxml={xml_path}"],
        cwd=lab_dir,
        capture_output=True,
        text=True,
        timeout=PYTEST_TIMEOUT_S,
    )
    tests = []
    collection_error = None
    if xml_path.exists():
        ts = ET.parse(xml_path).getroot().find("testsuite")
        for tc in ts.iter("testcase"):
            name = tc.get("name")
            outcome, detail = "passed", ""
            for node in list(tc):
                if node.tag in ("failure", "error"):
                    outcome = node.tag  # "failure" or "error"
                    detail = (node.get("message") or "") + "\n" + (node.text or "")
                    break
                if node.tag == "skipped":
                    outcome = "skipped"
                    break
            # pytest's junitxml reports a collection error as a single
            # testcase named after the module with an <error>.
            if outcome == "error" and "collection" in detail.lower():
                collection_error = detail
            tests.append({"name": name, "outcome": outcome, "detail": detail})
    return {
        "returncode": proc.returncode,
        "tests": tests,
        "collection_error": collection_error,
        "stdout_tail": proc.stdout[-2000:],
        "stderr_tail": proc.stderr[-2000:],
    }


# ---------------------------------------------------------------------------
# RED / GREEN verdicts
# ---------------------------------------------------------------------------
def check_red(lab: dict, result: dict) -> dict:
    spec = lab["red"]
    tests = result["tests"]
    marker = spec["marker"]

    def failed_as_documented(t: dict) -> bool:
        return t["outcome"] in ("failure", "error") and marker in t["detail"]

    if spec["kind"] == "collection_error":
        ok = (
            result["collection_error"] is not None
            and marker in result["collection_error"]
            and all(t["outcome"] != "passed" for t in tests)
        )
        return {
            "pass": ok,
            "detail": (
                f"collection error naming {marker!r} as shipped"
                if ok else
                f"expected a collection error naming {marker!r}; got "
                f"{[(t['name'], t['outcome']) for t in tests]}"
            ),
        }

    if spec["kind"] == "all_fail":
        ok = (
            len(tests) == lab["n_tests"]
            and all(failed_as_documented(t) for t in tests)
        )
        bad = [t["name"] for t in tests if not failed_as_documented(t)]
        return {
            "pass": ok,
            "detail": (
                f"all {lab['n_tests']} tests fail with {marker!r} as shipped"
                if ok else
                f"expected all {lab['n_tests']} to fail with {marker!r}; "
                f"deviants: {bad}"
            ),
        }

    if spec["kind"] == "fail_except":
        allowed = set(spec["allowed_pass"])
        passed = [t["name"] for t in tests if t["outcome"] == "passed"]
        failed_ok = [t for t in tests if failed_as_documented(t)]
        ok = (
            len(tests) == lab["n_tests"]
            and set(passed) == allowed
            and len(failed_ok) == lab["n_tests"] - len(allowed)
        )
        return {
            "pass": ok,
            "detail": (
                f"{len(failed_ok)} fail with {marker!r}, "
                f"{sorted(allowed)} pass (documented trap) as shipped"
                if ok else
                f"expected {lab['n_tests'] - len(allowed)} failures with "
                f"{marker!r} plus passes {sorted(allowed)}; got passes "
                f"{passed}, failures "
                f"{[t['name'] for t in tests if t['outcome'] in ('failure', 'error')]}"
            ),
        }

    raise AssertionError(f"unknown red kind {spec['kind']}")


def check_green(lab: dict, result: dict) -> dict:
    tests = result["tests"]
    passed = [t for t in tests if t["outcome"] == "passed"]
    not_passed = [t for t in tests if t["outcome"] != "passed"]
    ok = len(tests) == lab["n_tests"] and not not_passed
    return {
        "pass": ok,
        "detail": (
            f"all {lab['n_tests']} tests pass with the Appendix B key"
            if ok else
            f"expected {lab['n_tests']} passes; "
            f"{[(t['name'], t['outcome']) for t in not_passed]} did not pass"
        ),
    }


# ---------------------------------------------------------------------------
# Temp-tree builders
# ---------------------------------------------------------------------------
def fresh_code_tree(tag: str) -> Path:
    """Copy the whole code/ tree to a temp dir; return the temp code dir."""
    workdir = Path(tempfile.mkdtemp(prefix=f"lab-double-run-{tag}-"))
    dest = workdir / "code"
    shutil.copytree(
        CODE, dest,
        ignore=shutil.ignore_patterns("__pycache__", ".pytest_cache"),
    )
    return workdir


def splice_key(workdir: Path, lab: dict) -> None:
    """Apply the Appendix B key to the temp tree (GREEN run only)."""
    lab_dir = workdir / "code" / lab["chapter"]
    key_src = APP_B / lab["key"]
    if not key_src.exists():
        raise FileNotFoundError(f"answer key missing: {key_src}")
    splice = lab["splice"]
    if "copy_as" in splice:
        # Lab 1: the key IS the module the lab imports.
        shutil.copy(key_src, lab_dir / splice["copy_as"])
    else:
        # Labs 2-4: copy the key in, then patch the stubs via conftest.
        key_dest = lab_dir / lab["key"]
        shutil.copy(key_src, key_dest)
        test_module = Path(lab["test_file"]).stem
        key_module = key_dest.stem
        patch_lines = "\n".join(
            f"_lab.{attr} = _key.{dotted.split('.', 1)[1]}"
            for attr, dotted in splice["patch"].items()
        )
        (lab_dir / "conftest.py").write_text(
            CONFTEST_TEMPLATE.format(
                test_module=test_module,
                key_module=key_module,
                patch_lines=patch_lines,
            )
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(
        description="Run each lab's tests twice: RED as shipped, GREEN with keys.")
    ap.add_argument("--json", default=None,
                    help="write the machine-readable report to PATH")
    ap.add_argument("--lab", default=None, choices=[l["chapter"] for l in LABS],
                    help="run only one lab (default: all)")
    args = ap.parse_args()

    labs = [l for l in LABS if args.lab is None or l["chapter"] == args.lab]
    report = {"labs": [], "ok": True}
    failures = []

    for lab in labs:
        entry = {"chapter": lab["chapter"], "lab": lab["lab"]}
        lab_dir_name = lab["chapter"]

        # -- RED: as shipped ------------------------------------------------
        red_work = fresh_code_tree(f"{lab_dir_name}-red")
        try:
            red_result = run_pytest(red_work / "code" / lab_dir_name)
        finally:
            shutil.rmtree(red_work, ignore_errors=True)
        red = check_red(lab, red_result)
        entry["red"] = {
            "pass": red["pass"],
            "detail": red["detail"],
            "n_tests": len(red_result["tests"]),
        }

        # -- GREEN: with the Appendix B key --------------------------------
        green_work = fresh_code_tree(f"{lab_dir_name}-green")
        try:
            splice_key(green_work, lab)
            green_result = run_pytest(green_work / "code" / lab_dir_name)
        finally:
            shutil.rmtree(green_work, ignore_errors=True)
        green = check_green(lab, green_result)
        entry["green"] = {
            "pass": green["pass"],
            "detail": green["detail"],
            "n_tests": len(green_result["tests"]),
        }

        entry["ok"] = red["pass"] and green["pass"]
        report["labs"].append(entry)
        if not entry["ok"]:
            report["ok"] = False
            failures.append(lab["chapter"])

        status = "OK " if entry["ok"] else "FAIL"
        print(f"[{status}] {lab['chapter']} {lab['lab']}")
        print(f"        RED:   {'pass' if red['pass'] else 'FAIL'} — {red['detail']}")
        print(f"        GREEN: {'pass' if green['pass'] else 'FAIL'} — {green['detail']}")

    if args.json:
        Path(args.json).write_text(json.dumps(report, indent=2) + "\n")
        print(f"\nreport: {args.json}")

    # Guard: the harness must never leave keys in the shipped tree.
    leaked = []
    for lab in labs:
        splice = lab["splice"]
        probe = CODE / lab["chapter"] / splice.get("copy_as", lab["key"])
        if probe.exists():
            leaked.append(str(probe))
    if leaked:
        print(f"\nERROR: key material leaked into the shipped tree: {leaked}")
        return 1

    print()
    if report["ok"]:
        print("DOUBLE-RUN COMPLETE: every lab RED as shipped, GREEN with keys.")
        return 0
    print(f"DOUBLE-RUN FAILED for: {', '.join(failures)}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
